### ISSUE TITLE
data_process function error in (nrow(exp_data)!=length(unique(exp_data[,1])))

### ISSUE THREAD

**Issue by evelynb4565** [TMSWCChenglab/LipidSigR#1]
When using the default options for all arguments in `data_process()` function, this error appeared:

"The lipids name (features) must be unique"

Upon looking at the source code, I found the source of the error: 

at **line 45 in data_process:** 

 ```
if(nrow(exp_data)!=length(unique(exp_data[,1]))){
    stop("The lipids name (features) must be unique")

```
`length()` function refers to the number of columns, not the rows in the data frame. Although my rows are all unique, I was still getting the error that the number of rows did not match the number of unique elements. When I changed `length()` to `nrow()`, the function worked successfully and returned a processed data frame. 

My edit would be:

```
 if(nrow(exp_data)!=nrow(unique(exp_data[,1]))){
    stop("The lipids name (features) must be unique")
```

**Comment by TMSWCChenglab** [comment]
Thanks for your reply.
I think this is a problem with the data format. If the expdata format is matrix/data.frame, the original code will be fine.
When the expdata format is tibble, an error will occur. At present, we have fixed this error and will check our code for the tibble format, thanks.
